### ISSUE TITLE
Don't judge xD new module

### ISSUE THREAD

**Issue by boginw** [mrkno/Kassy#105]
I have no idea of how to properly use GitHub. But gotta start somewhere.

I created a WHOIS module for the platform. I didn't know how to commit to this rep, so I somehow managed to fork and commit to another rep.

https://github.com/boginw/Kassy

Could someone yell at me, and then tell me if the code is good enough?

**Comment by mrkno** [comment]
For a first module, there is nothing obviously wrong with your code. It would probably be better suited to being a KPM module, the https://github.com/mrkno/HelloKassy repo will probably help with that.

In terms of migrating your code to a kpm repo do the following:
- Create a new github repository (https://github.com/new)
- In the command line, cd into your `whois` folder
- Follow the instructions for existing code on the new github repo page

Also it would probably pay not to commit your `config.json`. Currently it has nothing in it but if you choose to use it in the future you could end up committing sensitive data.

In order to maintain future backwards compatibility, I suggest changing the line:
`"startup": "whois"` in your `kassy.json` to `"startup": "whois.js"`.

**Comment by boginw** [comment]
Let me just thank you first, for being patient :) Secondly, have I done it correctly?
https://github.com/boginw/KassyWhois

**Comment by mrkno** [comment]
Yup, seems to work fine in test and facebook. Doesn't seem to work on slack but not sure why (given it works on facebook and test its a problem at our end not yours)
