### ISSUE TITLE
apiKey error

### ISSUE THREAD

**Issue by NekoKamiDesu** [mrkno/Kassy#124]
After I put an apiKey into the config.json file, signin to facebook always fails. Any ideas?

Heres my config.json (with a few things hidden for obvious reasons)
`{
	"output": {
		"facebook": {
			"username": "*********@gmail.com",
			"password": "********",
			"testingName": "Bot",
			"commandPrefix": "!"
			"apiKey": "*********"
		}
	}
}`

**Comment by mrkno** [comment]
Without seeing the exact output ([with debugging enabled as per the documentation](https://github.com/mrkno/Kassy/blob/master/doc/DebuggingAndLogging.md)) I cannot say what the issue is. If you are trying to use facebook be aware of the issue currently affecting the upstream dependency where sign-in may/may not succeed and messages are never received, there is a few work arounds in the issue tracker of [facebook-chat-api](https://github.com/Schmavery/facebook-chat-api/issues).

**Comment by mrkno** [comment]
Please check if https://github.com/mrkno/Kassy/commit/c9ac47ddb5d6846de19902d1f36c1914c21d3bcf fixed your issue

(`git pull && npm update`)

**Comment by NekoKamiDesu** [comment]
OK! I'll check when I get home, if problem still persists, I'll look into the logs and upload them!

**Comment by NekoKamiDesu** [comment]
It seems like it doesnt like my config file.

> No or invalid configuration file found at "config.json'.

Heres the full log
[.log Download link](http://puu.sh/ooTep/91ca910a30.log)

**Comment by NekoKamiDesu** [comment]
Nevermind! it seems like i was stupid and decided to put the apiKey in the sys config. Everything is fine now.
