### ISSUE TITLE
[Suggestion] Spam prevention

### ISSUE THREAD

**Issue by NekoKamiDesu** [mrkno/Kassy#128]
There could be some spam prevention
I.E. if the bot is outputting every 50ms have it not take input for a second etc.
(And of course make it togglable via command/cfg file)

**Comment by mrkno** [comment]
A rate limiter like this would be possible using a core module.

**Comment by NekoKamiDesu** [comment]
@mrkno Elaborate? I'm not sure how i would tackle this.

**Comment by mrkno** [comment]
@NekoKamiDesu I would suggest taking the [disable core module](https://github.com/mrkno/Kassy/blob/master/core/core_modules/disable.js) and change the enable/disable to be based on frequency rather than a simple binary toggle.

I would modify the match method to match when the time/frequency is too high.

Core modules operate very similar to [normal modules](https://github.com/mrkno/Kassy/blob/master/doc/ModuleCreation.md), with the main differences being that they can modify variables within `platform.js` and must be self contained within a single `.js` file.

**Comment by NekoKamiDesu** [comment]
@mrkno 
I tried making my own but failed; since i don't know much in coding and just exploring.
-----
var disabled = false
var startup = true
var counter = 0

exports.match = function(text, commandPrefix) {
	return disabled || text.startsWith (commandPrefix);
};

exports.run = function(api, event) {
		if (disabled) {
			api.sendMessage('Enabled.', event.thread_id);
			disabled = !disabled;
		}
		else if (startup) {
			var variable;
			function resetcounter() {
				variable = setInterval(clearcounter, 1000);
			}
			function clearcounter() {
				var counter = 0;
			}
			startup = !startup;
		}
		else {
			if (counter > 2) {
				disabled = !disabled;
				api.sendMessage('Disabled.', event.thread_id);
			}
			else {
				counter += 1;
			}
		}
	return false;
};
-----
The code is stuck on permanent disable; as in none of my modules work.
Any help from ANYONE would be appreciated! (my friends nearly always spam when the bot comes online)

**Comment by ParasDPain** [comment]
@NekoKamiDesu I'd recommend reverting the code in `exports.run` to it's original state and modifying `export.match` to only return when consecutive calls to it method reach the counter

Something like this might do the job
```
exports.match = function(text, commandPrefix) {
    // Check for command match first and then increment counter and check it's value
    if(text === commandPrefix + 'disable' && counter++ > 1000){
        counter = 0; // reset counter
        return true;
    }
};
```

**Comment by NekoKamiDesu** [comment]
@ParasDPain 
I'll give it a try once i get home
(along with editing export.run)
Thanks!

**Comment by mrkno** [comment]
@NekoKamiDesu if you successfully work it out, it is a feature which could be good to merge into the main project.

The main reason your original code does not work is because `exports.run` is only called if `exports.match` returns `true` - this will only occur in a permanent disable because you have not modified the method. The refactor @ParasDPain did of your code should be a good start at correcting the problem.

**Comment by NekoKamiDesu** [comment]
@ParasDPain 
It seems that it doesn't like 'prevDate' being referenced before it is set
I'll look into getting a solution.
`ERR! ERROR in listen -->  ReferenceError: prevDate is not defined
ERR! ERROR in listen -->      at Platform.exports.match (sapm.js:10:33)
ERR! ERROR in listen -->      at Platform.messageRxd (platform.js:52:39)
ERR! ERROR in listen -->      at facebook.js:90:6
ERR! ERROR in listen -->      at parsePackets (C:\Users\Koret\Desktop\IzunaBot\node_modules\facebook-chat-api\src\listen.js:161:22)
ERR! ERROR in listen -->      at Array.forEach (native)
ERR! ERROR in listen -->      at C:\Users\Koret\Desktop\IzunaBot\node_modules\facebook-chat-api\src\listen.js:108:12
ERR! ERROR in listen -->      at tryCatcher (C:\Users\Koret\Desktop\IzunaBot\node_modules\bluebird\js\main\util.js:26:23)
ERR! ERROR in listen -->      at Promise._settlePromiseFromHandler (C:\Users\Koret\Desktop\IzunaBot\node_modules\bluebird\js\main\promise.js:507:31)
ERR! ERROR in listen -->      at Promise._settlePromiseAt (C:\Users\Koret\Desktop\IzunaBot\node_modules\bluebird\js\main\promise.js:581:18)
ERR! ERROR in listen -->      at Promise._settlePromises (C:\Users\Koret\Desktop\IzunaBot\node_modules\bluebird\js\main\promise.js:697:14)
ERR! ERROR in listen -->      at Async._drainQueue (C:\Users\Koret\Desktop\IzunaBot\node_modules\bluebird\js\main\async.js:123:16)
ERR! ERROR in listen -->      at Async._drainQueues (C:\Users\Koret\Desktop\IzunaBot\node_modules\bluebird\js\main\async.js:133:10)
ERR! ERROR in listen -->      at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Koret\Desktop\IzunaBot\node_modules\bluebird\js\main\async.js:15:14)
ERR! ERROR in listen -->      at tryOnImmediate (timers.js:534:15)
ERR! ERROR in listen -->      at processImmediate [as _immediateCallback] (timers.js:514:5)
ERR! ERROR in listen -->   [ReferenceError: prevDate is not defined]
undefined`

**Comment by ParasDPain** [comment]
@NekoKamiDesu That was merely a suggestion on how to approach the problem. `prevDate` needs to be declared globally before it's used. 
Please don't blindly copy-paste code, it is highly dangerous if not downright risky!

I recommend going through a few JavaScript tutorials. You can find good material [here ](http://stackoverflow.com/questions/11246/best-resources-to-learn-javascript) or if you prefer reading [this](http://eloquentjavascript.net/) is a good online source :+1:

**Comment by NekoKamiDesu** [comment]
@ParasDPain 
First thing i did was declare it :p
I knew i was doing with the blind copy and paste

**Comment by ParasDPain** [comment]
Great :+1: Do make a pull request when you complete the implementation :)

**Comment by NekoKamiDesu** [comment]
@ParasDPain 
I modified it a bit because no response was coming through; no disable or sendMessage in exports.run
When i put the sendMessage before the counter, it sent nothing...
I am very confused. (I may be missing something really simple)
```
exports.match = function(api, event, text, commandPrefix) {
    if(text === commandPrefix + 'disable') {
        return true; // return if the whole command was called
    }
    else if(text.startsWith(commandPrefix)) { // else perform a frequency check
        // Increment counter if the consecutive calls are between 1000ms
		api.sendMessage('tick', event.thread_id)
        counter += Date.now() - prevDate <= 1000 ? 1 : 0; 
        prevDate = Date.now(); // update prevDate either way

         // set a custom threshold value for the counter to execute on
        if(counter > 2) {
            counter = 0; // reset counter
            disabled = !disabled; 
            return true; // at this point export.run will need slight tweaking
        }
    }
};
```

**Comment by mrkno** [comment]
@NekoKamiDesu the signature for the `exports.match` core module method is `text, commandPrefix`, not `api, event, text, commandPrefix`.

I imagine the reason it does nothing is because it crashes. Calling a method which is `null` or `undefined` will throw an exception, so calling `api.sendMessage` (where `api` is really `text` - a string that knows nothing about `sendMessage`) is not going to get very far.

I too have other things to be doing otherwise I would spend more time helping.

**Comment by ParasDPain** [comment]
I've added the feature to [`disable.js`](https://github.com/ParasDPain/Kassy/blob/master/core/core_modules/disable.js) and the `disabled` state is flicked as expected, just only it's failing to disable modules anymore. So if you can have a look @mrkno and point out the obvious

**Comment by mrkno** [comment]
@ParasDPain https://github.com/ParasDPain/Kassy/blob/master/core/core_modules/disable.js#L24 `return isDisabled;` rather than `return false;`

**Comment by ParasDPain** [comment]
Hahaha damn too obvious indeed :+1: Thanks

**Comment by mrkno** [comment]
@ParasDPain you changed the wrong `return`. It is the `match` function that should `return isDisabled;` not the `run` which should probably `return false;`.

**Comment by ParasDPain** [comment]
Since in my implementation `exports.run` only sends the chat message, returning `isDisabled` from `exports.match` only controls the sending of the message. I've tried returning differently but it still doesn't disables the module because the match only checks for `commandPrefix`

I think the return value from the `run` function aborts calling other modules in `platform.js` in these lines
```javascript
// Run core modules in platform mode
for (var i = 0; i < this.coreModules.length; i++) {
   if (this.coreModules[i].match.apply(this, matchArgs)) {
      var temp = !this.coreModules[i].run.apply(this, runArgs);
      abort = abort || temp;
    }
}
if (abort) {
    return;
}
```
I might be able to get to the bottom of this if you can elaborate on how the disable feature works
