### ISSUE TITLE
Module dependencies to be installed during kpm install

### ISSUE THREAD

**Issue by ParasDPain** [mrkno/Kassy#137]
I'm sure this has been addressed before, but just so I can figure out my future modules.

How should one manage module dependencies if it'll be provided via kpm? 
Is it be possible to install module dependencies to **Node JS** while installing the module through `kpm` or does `/kpm update` installs them automatically?

**Comment by mrkno** [comment]
@ParasDPain sorry for the delay getting back to you on this. The reason why we have the `require.safe` (soon to be merged with normal `require`) is so that you don't need to worry about module dependencies. The first time your module is loaded it will automatically install the dependencies for you if it can't find them. As long as you use `require.safe` this will be automatic so nothing more needs to be done by you.

**Comment by ParasDPain** [comment]
Ohh! I understand now, thanks
